import type { AgentRole } from "./types";

/**
 * TradMode agent roster — 23 named Grok-agent roles.
 * Scaffolding + interfaces only. Live Grok calls require env keys (see each envKey).
 */
export const AGENT_ROSTER: AgentRole[] = [
  {
    index: 1,
    id: "conductor",
    name: "Conductor",
    codename: "Grok-01 Conductor",
    domain: "orchestration",
    summary: "Top-level task router across the 23-agent roster.",
    responsibilities: ["Route intents", "Assign owners", "Resolve conflicts", "Emit run plans"],
    envKey: "GROK_API_KEY",
    status: "scaffolded",
  },
  {
    index: 2,
    id: "market-scout",
    name: "Market Scout",
    codename: "Grok-02 Scout",
    domain: "market-data",
    summary: "Discovers BTC 15m windows via Gamma and flags gaps.",
    responsibilities: ["Slug discovery", "Window alignment", "Liquidity notes"],
    status: "scaffolded",
  },
  {
    index: 3,
    id: "price-auditor",
    name: "Price Auditor",
    codename: "Grok-03 Auditor",
    domain: "market-data",
    summary: "Ensures UI never shows invented Polymarket prices.",
    responsibilities: ["Validate outcomePrices", "Empty-state honesty", "Stale data warnings"],
    status: "scaffolded",
  },
  {
    index: 4,
    id: "btc-spot-ref",
    name: "BTC Spot Reference",
    codename: "Grok-04 Spot",
    domain: "market-data",
    summary: "Pulls public BTC/USD reference (Coinbase) for context only.",
    responsibilities: ["Spot fetch", "Clock sync labels"],
    status: "scaffolded",
  },
  {
    index: 5,
    id: "research-macro",
    name: "Macro Research",
    codename: "Grok-05 Macro",
    domain: "research",
    summary: "High-level BTC regime notes for 15m bias (non-advisory).",
    responsibilities: ["Regime tags", "Headline digest"],
    envKey: "GROK_API_KEY",
    status: "scaffolded",
  },
  {
    index: 6,
    id: "research-microstructure",
    name: "Microstructure Research",
    codename: "Grok-06 Micro",
    domain: "research",
    summary: "Order-book shape commentary from public CLOB reads.",
    responsibilities: ["Book imbalance notes", "Spread watch"],
    status: "scaffolded",
  },
  {
    index: 7,
    id: "sentiment",
    name: "Sentiment Probe",
    codename: "Grok-07 Sentiment",
    domain: "research",
    summary: "Optional social/news sentiment scaffold (key-gated).",
    responsibilities: ["Sentiment score placeholder", "Source attribution"],
    envKey: "GROK_API_KEY",
    status: "needs_key",
  },
  {
    index: 8,
    id: "risk-sizer",
    name: "Risk Sizer",
    codename: "Grok-08 Sizer",
    domain: "risk",
    summary: "Maps Conservative / Balanced / Aggressive caps to tickets.",
    responsibilities: ["Tier caps", "Balance fraction", "Confirm gates"],
    status: "scaffolded",
  },
  {
    index: 9,
    id: "risk-rails",
    name: "Risk Rails Guard",
    codename: "Grok-09 Rails",
    domain: "risk",
    summary: "Enforces kill switch, max loss, rate limits, position caps.",
    responsibilities: ["Rail checks", "Reject reasons", "Audit trail hooks"],
    status: "scaffolded",
  },
  {
    index: 10,
    id: "kill-switch-warden",
    name: "Kill Switch Warden",
    codename: "Grok-10 Warden",
    domain: "risk",
    summary: "Owns global halt state and re-arm confirmations.",
    responsibilities: ["Arm/disarm", "Broadcast halt", "Cooldown"],
    status: "scaffolded",
  },
  {
    index: 11,
    id: "execution-planner",
    name: "Execution Planner",
    codename: "Grok-11 Planner",
    domain: "execution",
    summary: "Builds Yes/No ticket intents for CLOB path (unsigned).",
    responsibilities: ["Side selection", "Size normalize", "Token id attach"],
    status: "scaffolded",
  },
  {
    index: 12,
    id: "execution-clerk",
    name: "Execution Clerk",
    codename: "Grok-12 Clerk",
    domain: "execution",
    summary: "Documents CLOB order submission path; live only with keys.",
    responsibilities: ["Order payload shape", "Idempotency keys"],
    envKey: "POLYMARKET_PRIVATE_KEY",
    status: "needs_key",
  },
  {
    index: 13,
    id: "fill-watcher",
    name: "Fill Watcher",
    codename: "Grok-13 Fills",
    domain: "execution",
    summary: "Watches post-trade state once CLOB auth is enabled.",
    responsibilities: ["Fill polling scaffold", "Partial fill notes"],
    envKey: "POLYMARKET_PRIVATE_KEY",
    status: "needs_key",
  },
  {
    index: 14,
    id: "monitor-latency",
    name: "Latency Monitor",
    codename: "Grok-14 Latency",
    domain: "monitoring",
    summary: "Tracks Gamma/CLOB fetch latency and error rates.",
    responsibilities: ["Timing", "Error budgets"],
    status: "scaffolded",
  },
  {
    index: 15,
    id: "monitor-health",
    name: "Health Monitor",
    codename: "Grok-15 Health",
    domain: "monitoring",
    summary: "Dashboard heartbeats for APIs, wallet, and rails.",
    responsibilities: ["Status strip", "Degraded modes"],
    status: "scaffolded",
  },
  {
    index: 16,
    id: "monitor-pnl",
    name: "PnL Monitor",
    codename: "Grok-16 PnL",
    domain: "monitoring",
    summary: "Daily loss tracking against tier max-loss rails.",
    responsibilities: ["Daily loss ledger", "Alert thresholds"],
    status: "scaffolded",
  },
  {
    index: 17,
    id: "compliance-scribe",
    name: "Compliance Scribe",
    codename: "Grok-17 Scribe",
    domain: "compliance",
    summary: "Labels demo vs live paths; records policy disclosures.",
    responsibilities: ["Demo banners", "Policy footnotes"],
    status: "scaffolded",
  },
  {
    index: 18,
    id: "geo-awareness",
    name: "Geo Awareness",
    codename: "Grok-18 Geo",
    domain: "compliance",
    summary: "Reminds operators of Polymarket geographic restrictions.",
    responsibilities: ["Restriction notice", "Link to docs"],
    status: "scaffolded",
  },
  {
    index: 19,
    id: "wallet-teller",
    name: "Wallet Teller",
    codename: "Grok-19 Teller",
    domain: "wallet",
    summary: "Deposit/withdraw UX with zero-fee policy enforcement.",
    responsibilities: ["Ledger updates", "No-fee policy", "Tx history"],
    status: "scaffolded",
  },
  {
    index: 20,
    id: "wallet-reconciler",
    name: "Wallet Reconciler",
    codename: "Grok-20 Reconcile",
    domain: "wallet",
    summary: "Reconciles trade debits/credits with ticket outcomes.",
    responsibilities: ["Balance integrity", "Tx audit"],
    status: "scaffolded",
  },
  {
    index: 21,
    id: "ux-chrome",
    name: "UX Chrome",
    codename: "Grok-21 Chrome",
    domain: "ux",
    summary: "Guards glassmorphism tokens and mobile-friendly layouts.",
    responsibilities: ["Token sync", "Responsive nav"],
    status: "scaffolded",
  },
  {
    index: 22,
    id: "figma-bridge",
    name: "Figma Bridge",
    codename: "Grok-22 Figma",
    domain: "ux",
    summary: "Keeps CSS/TS tokens mappable to Figma variables.",
    responsibilities: ["Token docs", "Handoff notes"],
    status: "scaffolded",
  },
  {
    index: 23,
    id: "ops-release",
    name: "Ops Release",
    codename: "Grok-23 Release",
    domain: "ops",
    summary: "Vercel deploy readiness and env checklist.",
    responsibilities: ["Env audit", "Build health", "Rollback notes"],
    status: "scaffolded",
  },
];

export function getAgent(id: string): AgentRole | undefined {
  return AGENT_ROSTER.find((a) => a.id === id);
}

export function resolveAgentLiveStatus(agent: AgentRole): AgentRole {
  if (!agent.envKey) return { ...agent, status: "scaffolded" };
  const present =
    typeof process !== "undefined" &&
    !!process.env[agent.envKey] &&
    process.env[agent.envKey]!.length > 0;
  return { ...agent, status: present ? "ready" : "needs_key" };
}
